/*
  ╔════════════════════════════════════════════════════════════════════╗
  ║                        ManualMode.h - Shadow-RC                   ║
  ║────────────────────────────────────────────────────────────────────║
  ║ Header file for Manual Mode control logic. This file declares     ║
  ║ setup and loop functions used to give the user full control       ║
  ║ over R2-D2 using standard RC joystick inputs.                     ║
  ║                                                                   
  ⚠️  DO NOT EDIT this file unless you know what you're doing.         ║
  It simply defines the interface used by the Master Control File.    ║
  ║                                                                   
  May the Force be with you, Builder.                                 ║
  ╚════════════════════════════════════════════════════════════════════╝
*/

#ifndef MANUALMODE_H
#define MANUALMODE_H

void setupManualMode();
void loopManualMode();

// Required for Sabertooth + SyRen serial motor control
#include <Sabertooth.h>
#include <SyRenSimplified.h>

// External motor controller objects (defined in ManualMode.cpp)
extern Sabertooth ST;            // For drive motors (motor 1 and 2)
extern Sabertooth domeMotor;    // For dome motor control

#endif






